### ISSUE TITLE
monthdelta dependency

### ISSUE THREAD

**Issue by baerbock** [TUW-GEO/merra#2]
Hi,

do I really need monthdelta from https://bugs.python.org/file13307/monthdelta.py as dependency?

**Comment by sebhahn** [comment]
seems like https://github.com/TUW-GEO/merra/blob/master/merra/interface.py#L31 is the only import, but actually never used in the code

@fzaussin could you please remove the dependency

**Comment by fzaussin** [comment]
@baerbock, as already commented by @sebhahn, _monthdelta_ is not actually being used in the current code. Thanks for pointing it out, I have now removed the dependency.
